name: crawl

on:
  schedule:
    - cron: '43 */8 * * *'
  workflow_dispatch:

jobs:
  get-cloudtrail:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          token: ${{secrets.PAT}}

      - name: INSTALL - python@3.11
        uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38  # v5.4.0
        with:
          python-version: '3.11'
      
      - id: get-topics
        run: |
          pip install -r requirements.txt
          python3 ./scrape.py

      - name: Commit and Push
        run: ./.github/commit-and-push.sh
        env:
          NAME: ${{ secrets.NAME }}
          EMAIL: ${{ secrets.EMAIL }}
